name: Generate Pixel Profile Card

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate CRT stats card
        uses: LuciNyan/pixel-profile/action@main
        with:
          crt_outputs: |
            dist/github-stats-crt?username=banda59&include_all_commits=true

      - name: Push generated cards to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
